# Generated by Django 4.2.4 on 2023-08-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_at',
            field=models.DateTimeField(blank=True, verbose_name="Date of end your experience (If not the end that don't write a date)"),
        ),
    ]
