# Generated by Django 4.2.4 on 2023-08-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_app', '0002_alter_experience_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_at',
            field=models.DateTimeField(blank=True, verbose_name="Date of end your education (If not the end that don't write a date)"),
        ),
    ]
